# Тема 10. Декораторы и исключения.
Отчет по Теме #10 выполнила:
- Горюнова Алина Алексеевна
- ИВТ-22-1

| Задание | Лаб_раб | Сам_раб|
| ------ | ------ | ------|
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |


знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.


Лабораторные задания:	

1) Наверняка вы думаете, что декораторы - это какая-то бесполезная
вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100.
Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. 
Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот Декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто "возьмёт их из этого декоратора”). 
Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи.
Р.Ѕ. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания.

```python
from functools import lru_cache

@lru_cache(None)
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)
if __name__ == '__main__':
    print(fibonacci(100))
```
![Меню](https://github.com/Goryunova-a/Lab.rab./blob/main/pic10/pic1.png)
- Данная программа считает числа Фибоначчи для 100.


2) Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130.
Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.

```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]
        if age<0 or age>130:
            age = 'Недопустимый возраст'
        input_func(name, age)
    return output_func
@check
def personal_info(name, age):
    print(f"Name: {name} Age:{age}")
if __name__ == '__main__':
    personal_info('Владимир',38)
    personal_info('Александр',-5)
    personal_info('Петр', 138, 15, 48, 2)
```
![Меню](https://github.com/Goryunova-a/Lab.rab./blob/main/pic10/pic2.png)
- Данная программа пишет декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130.


3) Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string.
Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт.
Также дополнительно можете обернуть весь код функции в
try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.

```python
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')
if __name__ == '__main__':
    data([1, 15,'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])
```
![Меню](https://github.com/Goryunova-a/Lab.rab./blob/main/pic10/pic3.png)
- В данной программе используются исключения, котрые исключают неподходящий тип данных. В конце выводится информация: есть ли ошибка или программа выполнена


4) Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться "Успешная регистрация"

```python
class NegativeValueException(Exception):
    pass
def check_name(name):
    if len(name)>10:
        raise NegativeValueException('длинна более 10 символов')
    else:
        print('Успешная регистрация')
if __name__ == '__main__':
    name = '12345678910'
    check_name(name)
```
![Меню](https://github.com/Goryunova-a/Lab.rab./blob/main/pic10/pic4.png)
- Данная программа пишет исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться "Успешная регистрация"


5) После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: init () (вызывается при создании класса декоратора в программе) и call () (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.

```python
class SiteChecker:
    def __init__(self, func):
        print('>класс SiteChecker метод __init__ успешный запуск')
        self.func = func
    def __call__(self):
        print('>Проверка перед запуском', self.func.__name__)
        self.func()
        print('>Проверка безопасного выключения')
@SiteChecker
def site():
    print('Усердная работа сайта')
if __name__ == '__main__':
    print('>>Сайт запущен')
    site()
    print('>>Сайт выключен')
```
![Меню](https://github.com/Goryunova-a/Lab.rab./blob/main/pic10/pic5.png)
- Данная программа создаёт декоратор и выводит все логи в консоль.

Самостоятельные задания:

1) Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для
функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.

```python
import time
def timer(func):
    def wrapper(*args, **kwargs):
        start_time = time.perf_counter()
        result = func(*args, **kwargs)
        end_time = time.perf_counter()
        total_time = end_time - start_time
        print(f"Время выполнения функции {func.__name__}: {total_time:.4f} секунд")
        
        return result
    
    return wrapper
@timer
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
    print(fib2, end='')

if __name__ == "__main__":
    fibonacci()
```
![Меню](https://github.com/Goryunova-a/Lab.rab./blob/main/pic10/pic6.png)
- Данная программа показывает, что каждый раз, когда Вовочка будет вызывать функцию fibonacci(), декоратор будет выводить время её выполнения.


2) Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой
проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение ("бросить исключение") и вывести в консоль "файл пустой", а если он не пустой, то вывести информацию из файла.

```python
def read_file(filename):
    try:
        with open(filename, 'r') as file:
            data = file.read().strip()
            
            if not data:
                raise ValueError("Файл пустой")
                
            print(f"Информация из файла '{filename}':\n{data}")
    except FileNotFoundError:
        print(f"Файл '{filename}' не найден.")
    except ValueError as e:
        print(e)

read_file('empty_file.txt')
read_file('data_file.txt')
```
![Меню](https://github.com/Goryunova-a/Lab.rab./blob/main/pic10/pic7.png)
- Данная программа корректно обрабатывает ситуацию с пустым файлом и выводит соответствующие сообщения.


3) Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка "Неподходящий тип данных. Ожидалось число.". Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль.

```python
def sum():
    while True:
        try:
            user_input = input("Пожалуйста, введите число: ")
            number = float(user_input)
            result = 2 + number
            print(f"Сумма 2 и вашего числа равна: {result}")
            break 
        except ValueError:
            print("Неподходящий тип данных. Ожидалось число.")
sum()
```
![Меню](https://github.com/Goryunova-a/Lab.rab./blob/main/pic10/pic8.png)
- Данная программа корректно обрабатывает как правильные, так и неправильные значения ввода.

4) Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.
```python
from functools import wraps

def check_even_number(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if args[0] % 2 != 0:
            return f"{args[0]} не является четным числом."
        else:
            return func(*args, **kwargs)
    return wrapper
#определение функций, которые будут использоваться декоратором
@check_even_number
def square(number):
    return number * number

@check_even_number
def multiply_by_100(number):
    return number * 100
#тестируем программу
if __name__ == "__main__":
    #вызовы функций с четными числами
    print(square(8))      
    print(multiply_by_100(14))

    #вызовы функций с нечетными числами
    print(square(7))      
    print(multiply_by_100(15))  
```
![Меню](https://github.com/Goryunova-a/Lab.rab./blob/main/pic10/pic9.png)
- Данная программа показывает, что декоратор помогает предотвратить выполнение функций с неверными данными, обеспечивая контроль над входящими параметрами.


5) Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего
кода.
```python
class InvalidOperationError(Exception):
    #исключение, возникающее при попытке выполнить недопустимую операцию."""
    def __init__(self, message="Операция не может быть выполнена."):
        super().__init__(message)
#проверка деления на ноль
def divide(a, b):
    if b == 0:
        raise InvalidOperationError("Деление на ноль невозможно.")
    return a / b
#проверка диапазона значений
def check_range(value, min_value=0, max_value=100):
    if value < min_value or value > max_value:
        raise InvalidOperationError(f"Значение {value} должно находиться в диапазоне от {min_value} до {max_value}.")
    return value
#тестирование нашего исключения
if __name__ == "__main__":
    #тестирование для деления
    try:
        result = divide(10, 0)
    except InvalidOperationError as e:
        print(e)

    #нормальное деление
    result = divide(50, 5)
    print(result)

    #тестирование проверки диапазона
    try:
        checked_value = check_range(-1)
    except InvalidOperationError as e:
        print(e)

    checked_value = check_range(75)
    print(checked_value)
```
![Меню](https://github.com/Goryunova-a/Lab.rab./blob/main/pic10/pic10.png)
- Такое использование собственных исключений помогает сделать код более понятным и управляемым, особенно в сложных проектах, где требуется гибкость в обработке ошибок.
